# Apply to all files without committing:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
# format markdown files
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: "v4.0.0-alpha.8"
  hooks:
    - id: prettier
      types: [markdown]
      args: ["--prose-wrap", "always", "--print-width", "100"]

# Complain about coding style and format
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: "v0.7.3"
  hooks:
  - id: ruff
    args: [--fix]
    exclude: notebooks/
  - id: ruff-format
    exclude: notebooks/

# Check typehints
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.13.0
  hooks:
    - id: mypy
      additional_dependencies:
        - types-requests
        - types-PyYAML

  # Fix coding patterns from old Python versions
- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.0
  hooks:
    - id: pyupgrade
      args: [--py311-plus]

# Check that your "pyproject.toml" file working and that "poetry.lock" matches
- repo: https://github.com/python-poetry/poetry
  rev: "1.8.0"
  hooks:
    - id: poetry-check
    - id: poetry-lock
      args: [--check]

# Misc checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-json
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: debug-statements
    - id: check-merge-conflict
    - id: check-added-large-files
      args: ["--maxkb=1000"]
## Check for hardcoded secrets, eg passwords
#-   repo: https://github.com/zricethezav/gitleaks
#    rev: v8.5.2
#    hooks:
#      - id: gitleaks-docker
#
## Linting on Dockerfile
#-   repo: https://github.com/AleksaC/hadolint-py
#    rev: v2.9.3
#    hooks:
#      - id: hadolint
#
## Check security issues
#-   repo: https://github.com/PyCQA/bandit
#    rev: '1.7.4'
#    hooks:
#    - id: bandit
#      args: ["--exclude", "tests"]
#
## Linting for sql files
#- repo: https://github.com/sqlfluff/sqlfluff
#  rev: 0.11.2
#  hooks:
#    - id: sqlfluff-lint
